### ISSUE TITLE
[BUG]: Mod Settings doesn't open

### ISSUE THREAD

**Issue by R0rt1z2** [R0rt1z2/GrindrPlus#46]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When trying to access Mod Settings, Grindr crashes and restarts on its own.

### Steps to reproduce

1. Install GrindrPlus
2. Open Grindr
3. Open Settings
4. Click on `Mod Settings`

### Installation Method

LSPosed

### LSPosed version

1.9.2 (7024)

### LSPosed variant

JingMatrix

### ROM

LineageOS

### Android Version

13

### Security patch date

September 5, 2023

### Grindr version

24.19.0 (132462)

### GrindrPlus version

v3.2.5-24.19.0

### Relevant log output

```shell
12-22 16:52:08.455 20192 20192 D AndroidRuntime: Shutting down VM
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: Crash unexpectedly: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Rect.setEmpty()' on a null object reference
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at androidx.appcompat.widget.SwitchCompat.onMeasure(Unknown Source:106)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.view.View.measure(View.java:26496)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1240)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:723)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.view.View.measure(View.java:26496)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.view.View.measure(View.java:26496)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.view.View.measure(View.java:26496)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.view.View.measure(View.java:26496)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1442)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.widget.ScrollView.onMeasure(ScrollView.java:458)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.view.View.measure(View.java:26496)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.view.View.measure(View.java:26496)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(Unknown Source:0)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(Unknown Source:310)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.view.View.measure(View.java:26496)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:154)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.view.View.measure(View.java:26496)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.view.View.measure(View.java:26496)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.view.View.measure(View.java:26496)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.view.View.measure(View.java:26496)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:760)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.view.View.measure(View.java:26496)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4042)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2658)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2964)
12-22 16:52:08.456 20192 20192 I LSPosed-Bridge: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2371)
12-22 16:52:08.458 20192 20192 I LSPosed-Bridge: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9297)
12-22 16:52:08.458 20192 20192 I LSPosed-Bridge: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
12-22 16:52:08.458 20192 20192 I LSPosed-Bridge: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
12-22 16:52:08.458 20192 20192 I LSPosed-Bridge: 	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
12-22 16:52:08.458 20192 20192 I LSPosed-Bridge: 	at android.view.Choreographer.doFrame(Choreographer.java:832)
12-22 16:52:08.458 20192 20192 I LSPosed-Bridge: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
12-22 16:52:08.458 20192 20192 I LSPosed-Bridge: 	at android.os.Handler.handleCallback(Handler.java:942)
12-22 16:52:08.458 20192 20192 I LSPosed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-22 16:52:08.458 20192 20192 I LSPosed-Bridge: 	at android.os.Looper.loopOnce(Looper.java:201)
12-22 16:52:08.458 20192 20192 I LSPosed-Bridge: 	at android.os.Looper.loop(Looper.java:288)
12-22 16:52:08.458 20192 20192 I LSPosed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:7924)
12-22 16:52:08.458 20192 20192 I LSPosed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
12-22 16:52:08.458 20192 20192 I LSPosed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-22 16:52:08.458 20192 20192 I LSPosed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: FATAL EXCEPTION: main
12-22 16:52:08.458 20192 20192 E AndroidRuntime: Process: com.grindrapp.android, PID: 20192
12-22 16:52:08.458 20192 20192 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Rect.setEmpty()' on a null object reference
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at androidx.appcompat.widget.SwitchCompat.onMeasure(Unknown Source:106)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.view.View.measure(View.java:26496)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1240)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:723)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.view.View.measure(View.java:26496)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.view.View.measure(View.java:26496)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.view.View.measure(View.java:26496)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.view.View.measure(View.java:26496)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:1442)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.widget.ScrollView.onMeasure(ScrollView.java:458)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.view.View.measure(View.java:26496)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.view.View.measure(View.java:26496)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(Unknown Source:0)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(Unknown Source:310)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.view.View.measure(View.java:26496)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:154)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.view.View.measure(View.java:26496)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.view.View.measure(View.java:26496)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.view.View.measure(View.java:26496)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.view.View.measure(View.java:26496)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6981)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:760)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.view.View.measure(View.java:26496)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4042)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2658)
12-22 16:52:08.458 20192 20192 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2964)
12-22 16:52:08.460 20192 20192 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2371)
12-22 16:52:08.460 20192 20192 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9297)
12-22 16:52:08.460 20192 20192 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
12-22 16:52:08.460 20192 20192 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
12-22 16:52:08.460 20192 20192 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
12-22 16:52:08.460 20192 20192 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:832)
12-22 16:52:08.460 20192 20192 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
12-22 16:52:08.460 20192 20192 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
12-22 16:52:08.460 20192 20192 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-22 16:52:08.460 20192 20192 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
12-22 16:52:08.460 20192 20192 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
12-22 16:52:08.460 20192 20192 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7924)
12-22 16:52:08.460 20192 20192 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-22 16:52:08.460 20192 20192 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
12-22 16:52:08.460 20192 20192 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by R0rt1z2** [comment]
Fixed with https://github.com/R0rt1z2/GrindrPlus/commit/a8437504da1697e865d40a5b726d193406466ed3
